version: '3.8'

services:
 mysql:
  image: mysql:8
  container_name: real_estate_mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root_yeayyeab2
    MYSQL_DATABASE: real_estatedb
  ports:
    - "3306:3306"
  volumes:
    - mysql_data:/var/lib/mysql
  command: --pid-file=/var/lib/mysql/mysqld.pid

  backend:
    build:
      context: ./Backend
    container_name: real_estate_backend
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: yeayyeab2
      DB_NAME: real_estatedb
    ports:
      - "5000:80"

  frontend:
    build:
      context: ./frontend-2
    container_name: real_estate_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
